all:
	g++ mapper0.cpp -o mapper0
	g++ mapper1.cpp -o mapper1
	g++ mapper2.cpp -o mapper2
	g++ reducer0.cpp -o reducer0
	g++ reducer1.cpp -o reducer1
	g++ reducer2.cpp -o reducer2

clean:
	rm -f mapper0 mapper1 mapper2 reducer0 reducer1 reducer2